export type CategorySeed = {
  slug: string;
  nameRu: string;
  nameEn: string;
  sortOrder: number;
};

export const baseCategories: CategorySeed[] = [
  { slug: "coffee-and-tea", nameRu: "Кофе и чай", nameEn: "Coffee and Tea", sortOrder: 10 },
  { slug: "fruits-and-berries", nameRu: "Фрукты и ягоды", nameEn: "Fruits and Berries", sortOrder: 20 },
  { slug: "vegetables-and-greens", nameRu: "Овощи и зелень", nameEn: "Vegetables and Greens", sortOrder: 30 },
  { slug: "desserts", nameRu: "Десерты", nameEn: "Desserts", sortOrder: 40 },
  { slug: "spices-and-sauces", nameRu: "Специи и соусы", nameEn: "Spices and Sauces", sortOrder: 50 },
  { slug: "bread-and-baking", nameRu: "Хлеб и выпечка", nameEn: "Bread and Baking", sortOrder: 60 },
  { slug: "cocktails-and-soda", nameRu: "Коктейли и газировка", nameEn: "Cocktails and Soda", sortOrder: 70 },
  { slug: "ice-cream", nameRu: "Мороженое", nameEn: "Ice Cream", sortOrder: 80 },
  { slug: "clothes", nameRu: "Одежда", nameEn: "Clothes", sortOrder: 90 },
  { slug: "shoes-and-accessories", nameRu: "Обувь и аксессуары", nameEn: "Shoes and Accessories", sortOrder: 100 },
  { slug: "fabrics-and-textures", nameRu: "Ткани и фактуры", nameEn: "Fabrics and Textures", sortOrder: 110 },
  { slug: "jewelry", nameRu: "Украшения", nameEn: "Jewelry", sortOrder: 120 },
  { slug: "cosmetics", nameRu: "Косметика", nameEn: "Cosmetics", sortOrder: 130 },
  { slug: "makeup-palettes", nameRu: "Палетки макияжа", nameEn: "Makeup Palettes", sortOrder: 140 },
  { slug: "skin-tones", nameRu: "Оттенки кожи", nameEn: "Skin Tones", sortOrder: 150 },
  { slug: "hair-colors", nameRu: "Цвета волос", nameEn: "Hair Colors", sortOrder: 160 },
  { slug: "flowers", nameRu: "Цветы", nameEn: "Flowers", sortOrder: 170 },
  { slug: "trees-and-leaves", nameRu: "Деревья и листья", nameEn: "Trees and Leaves", sortOrder: 180 },
  { slug: "forest", nameRu: "Лес", nameEn: "Forest", sortOrder: 190 },
  { slug: "sea-and-ocean", nameRu: "Море и океан", nameEn: "Sea and Ocean", sortOrder: 200 },
  { slug: "rivers-and-lakes", nameRu: "Реки и озера", nameEn: "Rivers and Lakes", sortOrder: 210 },
  { slug: "sky-and-clouds", nameRu: "Небо и облака", nameEn: "Sky and Clouds", sortOrder: 220 },
  { slug: "sunrise-and-sunset", nameRu: "Рассвет и закат", nameEn: "Sunrise and Sunset", sortOrder: 230 },
  { slug: "weather", nameRu: "Погода", nameEn: "Weather", sortOrder: 240 },
  { slug: "seasons", nameRu: "Времена года", nameEn: "Seasons", sortOrder: 250 },
  { slug: "space", nameRu: "Космос", nameEn: "Space", sortOrder: 260 },
  { slug: "stones-and-minerals", nameRu: "Камни и минералы", nameEn: "Stones and Minerals", sortOrder: 270 },
  { slug: "metals", nameRu: "Металлы", nameEn: "Metals", sortOrder: 280 },
  { slug: "fire-and-smoke", nameRu: "Огонь и дым", nameEn: "Fire and Smoke", sortOrder: 290 },
  { slug: "interior", nameRu: "Интерьер", nameEn: "Interior", sortOrder: 300 },
  { slug: "furniture", nameRu: "Мебель", nameEn: "Furniture", sortOrder: 310 },
  { slug: "household-items", nameRu: "Бытовые предметы", nameEn: "Household Items", sortOrder: 320 },
  { slug: "kitchenware", nameRu: "Посуда и кухня", nameEn: "Kitchenware", sortOrder: 330 },
  { slug: "office-and-stationery", nameRu: "Офис и канцелярия", nameEn: "Office and Stationery", sortOrder: 340 },
  { slug: "school", nameRu: "Школа", nameEn: "School", sortOrder: 350 },
  { slug: "books-and-paper", nameRu: "Книги и бумага", nameEn: "Books and Paper", sortOrder: 360 },
  { slug: "technology", nameRu: "Технологии", nameEn: "Technology", sortOrder: 370 },
  { slug: "gadgets", nameRu: "Гаджеты", nameEn: "Gadgets", sortOrder: 380 },
  { slug: "cars", nameRu: "Автомобили", nameEn: "Cars", sortOrder: 390 },
  { slug: "transport", nameRu: "Транспорт", nameEn: "Transport", sortOrder: 400 },
  { slug: "aviation", nameRu: "Авиация", nameEn: "Aviation", sortOrder: 410 },
  { slug: "sports", nameRu: "Спорт", nameEn: "Sports", sortOrder: 420 },
  { slug: "fitness", nameRu: "Фитнес", nameEn: "Fitness", sortOrder: 430 },
  { slug: "music", nameRu: "Музыка", nameEn: "Music", sortOrder: 440 },
  { slug: "cinema", nameRu: "Кино", nameEn: "Cinema", sortOrder: 450 },
  { slug: "animation", nameRu: "Анимация", nameEn: "Animation", sortOrder: 460 },
  { slug: "art-materials", nameRu: "Художественные материалы", nameEn: "Art Materials", sortOrder: 470 },
  { slug: "paintings", nameRu: "Живопись", nameEn: "Paintings", sortOrder: 480 },
  { slug: "photography", nameRu: "Фотография", nameEn: "Photography", sortOrder: 490 },
  { slug: "emotions", nameRu: "Эмоции", nameEn: "Emotions", sortOrder: 500 },
  { slug: "childhood", nameRu: "Детство", nameEn: "Childhood", sortOrder: 510 },
  { slug: "toys", nameRu: "Игрушки", nameEn: "Toys", sortOrder: 520 },
  { slug: "travel", nameRu: "Путешествия", nameEn: "Travel", sortOrder: 530 },
  { slug: "cities-at-night", nameRu: "Ночной город", nameEn: "City at Night", sortOrder: 540 },
  { slug: "retro", nameRu: "Ретро", nameEn: "Retro", sortOrder: 550 },
  { slug: "vintage", nameRu: "Винтаж", nameEn: "Vintage", sortOrder: 560 },
  { slug: "luxury", nameRu: "Роскошь", nameEn: "Luxury", sortOrder: 570 },
  { slug: "holidays", nameRu: "Праздники", nameEn: "Holidays", sortOrder: 580 },
  { slug: "wedding", nameRu: "Свадьба", nameEn: "Wedding", sortOrder: 590 },
  { slug: "garden", nameRu: "Сад", nameEn: "Garden", sortOrder: 600 },
  { slug: "animals", nameRu: "Животные", nameEn: "Animals", sortOrder: 610 },
  { slug: "birds", nameRu: "Птицы", nameEn: "Birds", sortOrder: 620 },
  { slug: "underwater-world", nameRu: "Подводный мир", nameEn: "Underwater World", sortOrder: 630 },
  { slug: "sweets-and-candy", nameRu: "Сладости и конфеты", nameEn: "Sweets and Candy", sortOrder: 640 },
  { slug: "tea-ceremony", nameRu: "Чайная церемония", nameEn: "Tea Ceremony", sortOrder: 650 },
  { slug: "perfume", nameRu: "Парфюм", nameEn: "Perfume", sortOrder: 660 },
  { slug: "ceramics", nameRu: "Керамика", nameEn: "Ceramics", sortOrder: 670 },
  { slug: "desert-and-sand", nameRu: "Пустыня и песок", nameEn: "Desert and Sand", sortOrder: 680 },
  { slug: "northern-lights", nameRu: "Северное сияние", nameEn: "Northern Lights", sortOrder: 690 }
];
